Update NFTDogs.sol
(fixed) Gives error:
TypeError: Function needs to specify overridden contract "ERC721URIStorage".
  --> NFTDogs.sol:72:9:
   |
72 |         override(ERC721, ERC721Enumerable)
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Note: This contract: 
  --> @openzeppelin/contracts/token/ERC721/extensions/ERC721URIStorage.sol:12:1:
   |
12 | abstract contract ERC721URIStorage is IERC4906, ERC721 {
   | ^ (Relevant source part starts here and spans across multiple lines).